### ISSUE TITLE
JPA Persistence not working

### ISSUE THREAD

**Issue by sirchnik** [FraunhoferIOSB/FAAAST-Registry#221]
## Description

When trying out the JPA Persistence I noticed that it isn't working because foreign key constraints are violated. Additionally the example docker-compose file is broken because the wrong spring.profile is used.

## Reproduction

<details>
<summary>docker-compose</summary>

```yml
services:
  faaast-registry:
    image: fraunhoferiosb/faaast-registry:1.1.0
    environment:
      - spring.profiles.active=jpa
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.datasource.driver=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - spring.datasource.username=root
      - spring.datasource.password=password
      - service.port=8090
      - server.ssl.enabled=false
    ports:
      - 8090:8090
    depends_on:
      - postgres
        #command: '-vvv'

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 8092:5432
```
</details>

<details>
<summary>example curl</summary>

```bash
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
      "administration": {
        "creator": {
          "keys": [
            {
              "type": "GlobalReference",
              "value": "http://anydomain.com/users/User99-1"
            }
          ],
          "referredSemanticId": null,
          "type": "ExternalReference"
        },
        "revision": "25",
        "templateId": null,
        "version": "12",
        "embeddedDataSpecifications": []
      },
      "assetKind": "Instance",
      "assetType": "AssetType99",
      "endpoints": [
        {
          "protocolInformation": {
            "endpointProtocol": "http",
            "endpointProtocolVersion": [
              "2.1"
            ],
            "href": "http://iosb.fraunhofer.de/IntegrationTest/Endpoints/AAS99",
            "securityAttributes": [
              {
                "key": "",
                "type": "NONE",
                "value": ""
              }
            ],
            "subprotocol": "https",
            "subprotocolBody": "any body",
            "subprotocolBodyEncoding": "UTF-8"
          },
          "interface": "http"
        }
      ],
      "globalAssetId": "http://iosb.fraunhofer.de/GlobalAssetId/IntegrationTest99",
      "id": "http://iosb.fraunhofer.de/IntegrationTest/AAS$RANDOM",
      "idShort": "IntegrationTest990",
      "specificAssetIds": [],
      "submodelDescriptors": [
        {
          "description": [],
          "displayName": [],
          "extensions": [],
          "administration": {
            "creator": null,
            "revision": "12",
            "templateId": null,
            "version": "1",
            "embeddedDataSpecifications": []
          },
          "endpoints": [
            {
              "protocolInformation": {
                "endpointProtocol": "http",
                "endpointProtocolVersion": [
                  "2.0"
                ],
                "href": "http://iosb.fraunhofer.de/Endpoints/Submodel99-1",
                "securityAttributes": [],
                "subprotocol": null,
                "subprotocolBody": null,
                "subprotocolBodyEncoding": null
              },
              "interface": "http"
            }
          ],
          "id": "http://iosb.fraunhofer.de/IntegrationTest/Submodel99-1",
          "idShort": "Submodel-99-1",
          "semanticId": {
            "keys": [
              {
                "type": "GlobalReference",
                "value": "http://iosb.fraunhofer.de/IntegrationTest/Submodel99-1/SemanticId"
              }
            ],
            "referredSemanticId": null,
            "type": "ExternalReference"
          },
          "supplementalSemanticId": []
        }
      ],
      "description": [
        {
          "language": "en-US",
          "text": "AAS 99 Integration Test"
        },
        {
          "language": "de-DE",
          "text": "AAS 99 Integrationstest"
        }
      ],
      "displayName": [
        {
          "language": "de-DE",
          "text": "Integration Test 99 Name"
        }
      ],
      "extensions": [
        {
          "name": "AAS99 Extension Name",
          "refersTo": [
            {
              "keys": [
                {
                  "type": "GlobalReference",
                  "value": "http://iosb.fraunhofer.de/IntegrationTest/Extension99/RefersTo1"
                }
              ],
              "referredSemanticId": null,
              "type": "ExternalReference"
            }
          ],
          "value": "AAS99 Extension Value",
          "valueType": "xs:string",
          "semanticId": {
            "keys": [
              {
                "type": "GlobalReference",
                "value": "http://iosb.fraunhofer.de/IntegrationTest/Extension99/SemanticId1"
              }
            ],
            "referredSemanticId": null,
            "type": "ExternalReference"
          },
          "supplementalSemanticIds": [
            {
              "keys": [
                {
                  "type": "GlobalReference",
                  "value": "http://iosb.fraunhofer.de/IntegrationTest/Extension99/SupplementalSemanticId1"
                }
              ],
              "referredSemanticId": null,
              "type": "ExternalReference"
            }
          ]
        }
      ]
    }' \
 http://localhost:8090/api/v3.0/shell-descriptors
```
</details>

## Expected

A shell descriptor should be created and visible at `http://localhost:8090/api/v3.0/shell-descriptors`.

## Output

```json
{"timestamp":"2025-01-03T15:48:47.444+00:00","status":500,"error":"Internal Server Error","message":"could not execute statement [ERROR: null value in column \"eid\" of relation \"asset_administration_shell_endpoints\" violates not-null constraint\n  Detail: Failing row contains (http://iosb.fraunhofer.de/IntegrationTest/AAS$RANDOM, 1232d7e0-d06b-4c00-99c0-0eedaa73d113, null, null, null).\n  Location: File: execMain.c, Routine: ExecConstraints, Line: 1987\n  Server SQLState: 23502] [insert into asset_administration_shell_endpoints (jpa_asset_administration_shell_descriptor_id,endpoints_id) values (?,?)]; SQL [insert into asset_administration_shell_endpoints (jpa_asset_administration_shell_descriptor_id,endpoints_id) values (?,?)]; constraint [eid\" of relation \"asset_administration_shell_endpoints]","path":"/api/v3.0/shell-descriptors"}
```

## Additional Context  

- The same request works fine when memory persistence is enabled.  
- I am reporting this issue solely for testing purposes, as I am currently verifying which AAS implementations are functioning. Therefore, I don't need a fix at this time.
